#cloud-config
package_update: true
packages:
  - curl
  - wget
  - htop
  - net-tools
  - iperf3

# SSH configuration
ssh_pwauth: true
disable_root: false
chpasswd:
  expire: false
  users:
    - name: ${USER_NAME}
      password: password
      type: text
      ssh_authorized_keys:
        - ${SSH_PUBLIC_KEY}

# SSH Keys
ssh_authorized_keys:
  - ${SSH_PUBLIC_KEY}

runcmd:
  # 0. Configure SSH for password authentication only
  - |
    cat > /etc/ssh/sshd_config << 'EOSSH'
    Port 22
    PermitRootLogin yes
    PubkeyAuthentication yes
    PasswordAuthentication yes
    PermitEmptyPasswords no
    ChallengeResponseAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/openssh/sftp-server
    EOSSH
  - systemctl restart sshd
  
  # 1. Basic system setup
  - apt-get update
  - apt-get upgrade -y
  
  # 1.5. Configure DNS
  - |
    if [ -n "${dns_servers}" ]; then
      echo "nameserver $(echo ${dns_servers} | sed 's/,/\nnameserver /g')" > /etc/resolv.conf
    fi
  
  # 2. Install and configure iperf3
  - apt-get install -y iperf3
  
  # 3. Create iperf3 service for server mode
  - |
    cat > /etc/systemd/system/iperf3-server.service << 'EOIPERF'
    [Unit]
    Description=iPerf3 Server
    After=network.target
    
    [Service]
    Type=simple
    User=nobody
    ExecStart=/usr/bin/iperf3 -s
    Restart=always
    RestartSec=5
    
    [Install]
    WantedBy=multi-user.target
    EOIPERF
  
  # 4. Enable and start iperf3 server
  - systemctl daemon-reload
  - systemctl enable iperf3-server
  - systemctl start iperf3-server