#cloud-config
package_update: true
packages:
  - net-tools
  - curl
  - wget
  - htop

# SSH configuration
ssh_pwauth: true
disable_root: false
chpasswd:
  expire: false
  users:
    - name: ${USER_NAME}
      password: password
      type: text

runcmd:
  - |
    cat > /etc/ssh/sshd_config << 'EOSSH'
    Port 22
    PermitRootLogin yes
    PubkeyAuthentication no
    PasswordAuthentication yes
    PermitEmptyPasswords no
    ChallengeResponseAuthentication no
    UsePAM yes
    X11Forwarding yes
    PrintMotd no
    AcceptEnv LANG LC_*
    Subsystem sftp /usr/lib/openssh/sftp-server
    EOSSH
  - systemctl restart sshd
  - apt-get update
  - apt-get upgrade -y
